# Generated by Django 5.2.8 on 2025-11-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_cnt', models.IntegerField(default=0)),
                ('avg_flowrate', models.FloatField(default=0)),
                ('avg_pressure', models.FloatField(default=0)),
                ('avg_temperature', models.FloatField(default=0)),
                ('type_distribution', models.JSONField(default=dict)),
            ],
        ),
    ]
