# Generated by Django 5.2.8 on 2025-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdataset',
            name='total_cnt',
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
