# Generated by Django 5.2.8 on 2025-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_equipmentdataset_total_cnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='max_flowrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='max_pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='max_temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='min_flowrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='min_pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='min_temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
