# Generated by Django 5.2.8 on 2025-11-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_equipmentdataset_max_flowrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='rows',
            field=models.JSONField(default=list),
        ),
    ]
